# Generated by Django 4.1.2 on 2022-11-17 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Wokout_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'workout_cat',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('workout_name', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exercise.wokout_group')),
            ],
            options={
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='Person_Workout',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_exercise.person')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exercise.workout')),
            ],
            options={
                'db_table': 'person_workout',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='workout',
            field=models.ManyToManyField(blank=True, through='app_exercise.Person_Workout', to='app_exercise.workout'),
        ),
    ]
