# Generated by Django 4.1.2 on 2022-12-09 01:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Person_Workout',
            fields=[
                ('person_workout', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exercise.person')),
            ],
            options={
                'db_table': 'person_workout',
            },
        ),
        migrations.CreateModel(
            name='Wokout_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'workout_cat',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('workout_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_exercise.wokout_group')),
            ],
            options={
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='Person_Workout_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('num_sets', models.SmallIntegerField(blank=True, default=0)),
                ('num_reps', models.SmallIntegerField(blank=True, default=0)),
                ('weight_used', models.SmallIntegerField(blank=True, default=0)),
                ('person_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exercise.person_workout')),
            ],
            options={
                'db_table': 'person_workout_data',
            },
        ),
        migrations.AddField(
            model_name='person_workout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exercise.workout'),
        ),
        migrations.AddField(
            model_name='person',
            name='workout',
            field=models.ManyToManyField(blank=True, through='app_exercise.Person_Workout', to='app_exercise.workout'),
        ),
        migrations.AddConstraint(
            model_name='person_workout',
            constraint=models.UniqueConstraint(fields=('person', 'workout'), name='person_workout_pk'),
        ),
    ]
