# Generated by Django 4.1.2 on 2022-12-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wokout_Group',
            new_name='Workout_Group',
        ),
    ]
